# --- my_shield_left.conf ---

# Assicura che questo lato sia sempre il Master (Central)
CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=y

# Abilita l'EC11 (Rotary Encoder)
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# (Opzionale) Abilita la comunicazione su porta USB se collegato via cavo
CONFIG_ZMK_USB=y
