# --- my_shield_right.conf ---

# Assicura che questo lato sia lo Slave (Peripheral)
CONFIG_ZMK_SPLIT_BLE_ROLE_PERIPHERAL=y

# Disabilita l'Encoder rotativo (non c'è fisicamente a destra)
CONFIG_EC11=n

# ABILITA IL TUO DRIVER CUSTOM IN C!
# Questa è la variabile che abbiamo definito nel tuo file Kconfig personalizzato
CONFIG_CUSTOM_CIRQUE_TRACKPAD=y
